version: "3.8"

services:
  db:
    image: postgres:13-alpine
    env_file:
      ./docker_config/.env.testing
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: 
      context: .
    image: django-webapp
    command: run
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
   
volumes: 
  pgdata:
  